parameters: {}
environment: {}
packages:
  - name: slack
    environment: {}
    parameters: {}
    actions:
      - name: msg
        main: ''
        runtime: 'go:1.20'
        environment: {}
        parameters: {}